"""Literal file contents for the generated demo repository (`seed/repo`).

Kept in one module so `build_seed.py` stays pure orchestration. Nothing here is ever
hand-edited in `seed/repo` -- delete the directory and regenerate.

The two revisions of `webhooks/delivery.py` are the spine of the demo story: v1 ships
a 5s retry backoff (PR #4100), v2 replaces it with 7s after an incident (PR #4821).
v2 deliberately rewrites enough of lines 20-40 that `git blame` over that range
resolves PR #4821 as the dominant commit while still reporting #4100 in
`BlameInfo.pr_numbers` -- that split is what the provenance graph is built to show.
"""

from __future__ import annotations

README = r'''# acme-payments

Merchant payments, settlement, and webhook delivery.

This is a synthetic repository generated by `seed/build_seed.py` for the Provenance
demo. It is not a real service.
'''

WEBHOOKS_INIT = r'''"""Outbound webhook delivery to merchant endpoints."""
'''

WEBHOOKS_TYPES = r'''"""Shared webhook value objects."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Delivery:
    """One webhook delivery attempt target."""

    merchant_id: str
    endpoint: str
    payload: dict
    idempotency_key: str
'''

WEBHOOKS_SIGNING = r'''"""Request signing for outbound webhooks.

Merchants verify an HMAC-SHA256 signature over the raw request body. The signing
secret is rotated per merchant; both the current and previous secret are accepted
during the rotation overlap so in-flight deliveries are not rejected.
"""

from __future__ import annotations

import hashlib
import hmac
import time

SIGNATURE_HEADER = "X-Acme-Signature"
TIMESTAMP_HEADER = "X-Acme-Timestamp"

# How long a signature stays acceptable to the receiving merchant. Deliberately
# generous: merchants batch-process webhooks and we do not want clock skew on their
# side to reject a legitimate delivery.
SIGNATURE_TOLERANCE_SECONDS = 300

# Overlap during which the previous signing secret is still honoured.
SECRET_ROTATION_OVERLAP_SECONDS = 86400


def sign_body(secret: str, body: bytes, timestamp: int | None = None) -> str:
    """Return the signature header value for `body` under `secret`."""
    timestamp = int(time.time()) if timestamp is None else timestamp
    signed_payload = f"{timestamp}.".encode() + body
    digest = hmac.new(secret.encode(), signed_payload, hashlib.sha256).hexdigest()
    return f"t={timestamp},v1={digest}"


def verify(secret: str, body: bytes, header: str, now: int | None = None) -> bool:
    """Constant-time verification of a signature header produced by `sign_body`."""
    now = int(time.time()) if now is None else now
    parts = dict(p.split("=", 1) for p in header.split(",") if "=" in p)
    try:
        timestamp = int(parts["t"])
    except (KeyError, ValueError):
        return False
    if abs(now - timestamp) > SIGNATURE_TOLERANCE_SECONDS:
        return False
    expected = sign_body(secret, body, timestamp).split("v1=", 1)[1]
    return hmac.compare_digest(expected, parts.get("v1", ""))
'''

SEARCH_INIT = r'''"""Search indexing pipeline."""
'''

SEARCH_INDEXER = r'''"""Document indexer for the merchant search index.

Indexing is best-effort: a document that fails to index is retried with exponential
backoff and then dropped onto the dead-letter queue rather than blocking the batch.
This retry policy is unrelated to webhook delivery retries -- different system,
different failure mode, different constants.
"""

from __future__ import annotations

import logging
import random
import time

log = logging.getLogger(__name__)

INDEX_RETRY_ATTEMPTS = 3
INDEX_RETRY_BASE_SECONDS = 0.5
INDEX_BATCH_SIZE = 500


def backoff_delay(attempt: int) -> float:
    """Jittered exponential backoff: 0.5s, 1s, 2s (plus up to 25% jitter)."""
    return INDEX_RETRY_BASE_SECONDS * (2 ** attempt) * (1 + random.random() * 0.25)


def index_batch(client, documents: list[dict]) -> list[dict]:
    """Index `documents`, returning whatever could not be indexed after retries."""
    pending = list(documents)
    for attempt in range(INDEX_RETRY_ATTEMPTS):
        failed = client.bulk_index(pending)
        if not failed:
            return []
        log.warning("index attempt %s left %s documents failing", attempt, len(failed))
        pending = failed
        time.sleep(backoff_delay(attempt))
    return pending
'''

UTILS_INIT = r'''"""Assorted helpers."""
'''

# The deliberate null case: nothing in the Slack corpus discusses this file.
UTILS_STRINGS = r'''"""Small string helpers used across the reporting exports."""

from __future__ import annotations

import re
import unicodedata

_NON_ALNUM = re.compile(r"[^a-z0-9]+")


def slugify(value: str) -> str:
    """Lowercase ASCII slug, collapsing runs of non-alphanumerics to a hyphen."""
    normalized = unicodedata.normalize("NFKD", value)
    ascii_only = normalized.encode("ascii", "ignore").decode("ascii")
    return _NON_ALNUM.sub("-", ascii_only.lower()).strip("-")


def truncate(value: str, limit: int) -> str:
    """Truncate to `limit` characters, appending an ellipsis when it was cut."""
    if len(value) <= limit:
        return value
    return value[: max(0, limit - 1)].rstrip() + "…"
'''

PAYMENTS_INIT = r'''"""Payments domain: capture, settlement, payouts."""
'''

PAYMENTS_SETTLEMENT = r'''"""Nightly settlement batch submission.

Settlement batches are submitted to the acquirer and acknowledged synchronously.
Large merchants submit batches big enough that the acquirer routinely takes over a
minute to acknowledge, so the timeout below is sized for the slowest observed
acknowledgement rather than the median.
"""

from __future__ import annotations

import logging

log = logging.getLogger(__name__)

# Raised from 30s after large-merchant batches began timing out mid-acknowledgement
# and settling twice on resubmit. See PR #3902.
SETTLEMENT_TIMEOUT_SECONDS = 90

MAX_BATCH_ENTRIES = 10000


def submit_batch(acquirer, entries: list[dict]) -> dict:
    """Submit one settlement batch and return the acquirer acknowledgement."""
    if len(entries) > MAX_BATCH_ENTRIES:
        raise ValueError(f"batch of {len(entries)} exceeds {MAX_BATCH_ENTRIES}")
    log.info("submitting settlement batch of %s entries", len(entries))
    return acquirer.submit(entries, timeout=SETTLEMENT_TIMEOUT_SECONDS)
'''

# --- webhooks/delivery.py, revision 1 -- PR #4100, 5s backoff ----------------
DELIVERY_V1 = r'''"""Webhook delivery to merchant endpoints.

Deliveries are attempted inline and retried with a fixed backoff when the
receiving endpoint is unavailable.
"""

from __future__ import annotations

import logging
import time

import requests

from .types import Delivery

log = logging.getLogger(__name__)

MAX_ATTEMPTS = 4
DELIVERY_TIMEOUT_SECONDS = 10

# Retry spacing between delivery attempts.
RETRY_BACKOFF_SECONDS = 5


def deliver(delivery: Delivery) -> bool:
    """Attempt delivery, retrying on transport failure."""
    for attempt in range(MAX_ATTEMPTS):
        if _attempt(delivery, attempt):
            return True
        time.sleep(RETRY_BACKOFF_SECONDS)
    return False


def _attempt(delivery: Delivery, attempt: int) -> bool:
    try:
        response = requests.post(
            delivery.endpoint,
            json=delivery.payload,
            timeout=DELIVERY_TIMEOUT_SECONDS,
            headers={"Idempotency-Key": delivery.idempotency_key},
        )
    except requests.RequestException as exc:
        log.warning("delivery attempt %s failed for %s: %s", attempt, delivery.merchant_id, exc)
        return False
    return response.status_code < 300
'''

# --- webhooks/delivery.py, revision 2 -- PR #4821, 7s backoff ----------------
DELIVERY_V2 = r'''"""Webhook delivery to merchant endpoints.

Deliveries are attempted inline and retried with a fixed backoff when the
receiving endpoint is unavailable.
"""

from __future__ import annotations

import logging
import time

import requests

from .types import Delivery

log = logging.getLogger(__name__)

MAX_ATTEMPTS = 4
DELIVERY_TIMEOUT_SECONDS = 10

# Retry spacing between delivery attempts. This has to clear an entire merchant
# failover window: at 5s we were still retrying inside the window and merchants
# accepted the same event twice (WEBHOOK-184, ENG-4821). 7s was measured against
# a real failover and held. Do not lower this without re-measuring the window.
RETRY_BACKOFF_SECONDS = 7


def deliver(delivery: Delivery) -> bool:
    """Attempt delivery, retrying on transport failure.

    The backoff is applied between attempts only -- never after the final attempt,
    which previously stalled the worker for a full RETRY_BACKOFF_SECONDS before
    giving up on a merchant that was never coming back.
    """
    for attempt in range(MAX_ATTEMPTS):
        if _attempt(delivery, attempt):
            return True
        if attempt < MAX_ATTEMPTS - 1:
            time.sleep(RETRY_BACKOFF_SECONDS)
    return False


def _attempt(delivery: Delivery, attempt: int) -> bool:
    try:
        response = requests.post(
            delivery.endpoint,
            json=delivery.payload,
            timeout=DELIVERY_TIMEOUT_SECONDS,
            headers={"Idempotency-Key": delivery.idempotency_key},
        )
    except requests.RequestException as exc:
        log.warning("delivery attempt %s failed for %s: %s", attempt, delivery.merchant_id, exc)
        return False
    return response.status_code < 300
'''

# Commit 0 -- everything that predates the demo story.
BASE_FILES: dict[str, str] = {
    "README.md": README,
    "webhooks/__init__.py": WEBHOOKS_INIT,
    "webhooks/types.py": WEBHOOKS_TYPES,
    "webhooks/signing.py": WEBHOOKS_SIGNING,
    "search/__init__.py": SEARCH_INIT,
    "search/indexer.py": SEARCH_INDEXER,
    "utils/__init__.py": UTILS_INIT,
    "utils/strings.py": UTILS_STRINGS,
    "payments/__init__.py": PAYMENTS_INIT,
}
